version: "3"
services:
  Fresh:
    image: beardedio/terraria:vanilla-latest
    ports:
      - "7776:7777"
    environment:
      world: Fresh.wld
    volumes:
      - /mnt/data/terraria/Fresh:/config
    container_name: "terraria_fresh"
    restart: unless-stopped
    tty: true
    stdin_open: true

  Classic:
    image: beardedio/terraria:vanilla-latest
    ports:
      - "7777:7777"
    environment:
      - world=Classic.wld
    volumes:
      - /mnt/data/terraria/Classic:/config
    container_name: "terraria_classic"
    restart: unless-stopped
    tty: true
    stdin_open: true

  Expert:
    image: beardedio/terraria:vanilla-latest
    ports:
      - "7778:7777"
    environment:
      - world=/config/Expert.wld
    volumes:
      - /mnt/data/terraria/Expert:/config
    container_name: "terraria_expert"
    restart: unless-stopped
    tty: true
    stdin_open: true

  Master:
    image: beardedio/terraria:vanilla-latest
    ports:
      - "7779:7777"
    environment:
      - world=/config/Master.wld
    volumes:
      - /mnt/data/terraria/Master:/config
    container_name: "terraria_master"
    restart: unless-stopped
    tty: true
    stdin_open: true

  Arcadia:
    image: beardedio/terraria:vanilla-latest
    ports:
      - "7780:7777"
    environment:
      - world=/config/Arcadia.wld
    volumes:
      - /mnt/data/terraria/Arcadia:/config
    container_name: "terraria_arcadia"
    restart: unless-stopped
    tty: true
    stdin_open: true

  Journey:
    image: beardedio/terraria:vanilla-latest
    ports:
      - "7781:7777"
    environment:
      - world=/config/Journey.wld
    volumes:
      - /mnt/data/terraria/Journey:/config
    container_name: "terraria_journey"
    restart: unless-stopped
    tty: true
    stdin_open: true
