apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraria-journey-pvc
  namespace: games
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: terraria-journey-pv
