apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terraria-expert-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: terraria-expert-pv
