apiVersion: v1
kind: PersistentVolume
metadata:
  name: terraria-expert-pv
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 100Mi
  local:
    path: /mnt/docker/volumes/terrariaExpert/_data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - as-r610
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
